services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $copyProperties: '%contao_content_templates.copy_properties%'
            $deleteEmptyArticles: '%contao_content_templates.delete_empty_articles%'
    
    InspiredMinds\ContaoContentTemplates\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,Event,Model,ContaoContentTemplatesBundle.php}
