services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoContentTemplates\:
        resource: ../src
        exclude: ../src/{ContaoManager,Event,Model,Resources}

    InspiredMinds\ContaoContentTemplates\Controller\:
        resource: ../src/Controller
        exclude: ../src/{ContentElement,FrontendModule}
        tags: ['controller.service_arguments']
